### ISSUE TITLE
Revise definition of `expected_countersigners` to include a snapshot of `signer_payload`

### ISSUE THREAD

**Issue by scouten-adobe** [creator-assertions/identity-assertion#114]
Per CAWG meeting on 28 May 2024, the definition of `expected_countersigners` should include a snapshot of `referenced_assertions` from other identity assertions.

Carried over from #103.

**Comment by nigelcearnshaw** [comment]
Just to be clear, and as described yesterday in PR 103, one way of including this data would be simply to substitute the value of the hash of the referenced assertions into the placeholder in the provisional manifest claim data instead of the zeroes currently assumed. From a security point of view this is certainly equivalent, but worth musing both approaches.
