### ISSUE TITLE
Add guidance regarding parsing and validation errors

### ISSUE THREAD

**Issue by scouten-adobe** [creator-assertions/identity-assertion#116]
Resolve TO DO issue in [§9.3.3, “Parsing and validation errors,”](https://creator-assertions.github.io/identity/1.0+trust-model/#_parsing_and_validation_errors) of upcoming trust model PR (#99) regarding parsing and validation errors.

**Comment by puhley** [comment]
The one thing that I would say about the parsing/validation pull request is that it is true that we can't tell people specifically what to do for their implementation. However, we can make their lives less difficult. A lot of specs try to be "flexible" by allowing as much as possible. This ultimately backfires because there is no way to validate free form text fields. When issues arise, it is hard to retrofit restrictive rules on freeform text fields because you break content and you can't put the genie back in the bottle. Therefore, we need to try to be specific in the early days and slowly open up as we get specific feature requests that require more flexibility.

**Comment by scouten-adobe** [comment]
Closed by #127.
