### ISSUE TITLE
Authoring vs. Ownership

### ISSUE THREAD

**Issue by lrosenthol** [creator-assertions/identity-assertion#46]
- [x] I have read the [CLA Document](https://github.com/creator-assertions/identity-assertion/blob/main/contributor-license.md) and I hereby sign the CLA.

----------------------------------------

One of the items that appears to have come up multiple times in the first CAWG meeting was around "ownership".  I would like to suggest that the WG *NOT* focus on ownership, but instead on *authorship*.   Ownership implies rights and legal standing with respect to the asset, while authorship does not - it simply declares the involvement of the party in the creation/editing of the content of asset.

**Comment by andyparsons** [comment]
I agree and lean strongly toward authorship, which may imply ownership, but does not necessarily indicate it. Given the fraught, contentious field of copyright during current times we should delay or entirely avoid rights.

**Comment by talltree** [comment]
Authorship would indeed be a much simpler assertion to tackle initially. Could "ownership" (e.g., copyright, other rights) be tackled by other C2PA assertion types (pardon my ignorance, I'm new to C2PA specs).

**Comment by jcollomosse** [comment]
I agree with all the above.  C2PA did a good job focusing exclusively on creation provenance i.e. authorship and avoided ownership and rights - not just for cleaner scoping but because other ecosystems do a good job focusing on them.  It would be good to continue this tight scoping, and 'link out' e.g. via assertions to those other ecosystems.  An example would be linking to ownership provenance in NFT, which we made some initial prototypes of in our paper. https://arxiv.org/abs/2304.04639  There we used the Asset reference assertion (ARA) but there's some reasonable question over whether that is entirely the correct thing to have used.

**Comment by scouten-adobe** [comment]
Per [26 February 2024 meeting](https://creator-assertions.github.io/meeting-notes/2024-02-26/#_15_min_authoring_vs_ownership_and_copyright), @scouten-adobe to draft a PR to clarify that identity assertion intends to convey authorship and not copyright or ownership.
